import assert from 'node:assert/strict';
import { CGOMachineABC } from './admin/cgo-machine-abc.js';
import './admin/cgo-machine-abc-bridge.js';
const st = CGOMachineABC.selfTest();
assert.equal(st.verified, true);
assert.equal(st.failed, 0);
assert.equal(st.total, 60);
const events=[];
const off=CGOMachineABC.observeTelemetry(e=>events.push(e));
const out=CGOMachineABC.process('upgrade-live-test');
off();
assert.equal(out.result.status, 'WELL_FORMED');
assert.equal(out.audit.status, 'VALID');
assert.equal(out.telemetry.route, 'A>B>C>D');
assert.equal(out.telemetry.routeStatus, 'COMPLETE');
assert.equal(out.telemetry.phases.length,4);
assert.equal(events.length,8);
assert.ok(out.telemetry.fingerprint);
console.log(JSON.stringify({selfTest:st,process:{status:out.result.status,audit:out.audit.status,route:out.telemetry.route,routeStatus:out.telemetry.routeStatus,events:events.length,fingerprint:out.telemetry.fingerprint}},null,2));
